name: Rename Images

on: push

jobs:
  update-readme:
    name: Rename images
    runs-on: ubuntu-latest
    steps:
      - uses: Parply/photo-renamer@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
